# Generated by Django 4.2.1 on 2023-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_form',
            new_name='validform',
        ),
    ]
