# Generated by Django 4.2.1 on 2023-08-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_valid_form_coupon_validform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='validform',
            new_name='valid_from',
        ),
    ]
